import * as routes from '../../constants/routes';

export const items = [
  {
    id: 1,
    type: 'navItem',
    icon: 'home',
    text: 'Home',
    link: routes.HOME,
    restricted: false,
  },
  {
    id: 2,
    type: 'navItem',
    icon: 'user',
    text: 'My Profile',
    link: routes.USER_PROFILE,
    restricted: true,
  },
  {
    id: 3,
    type: 'navItem',
    icon: 'user-plus',
    text: 'Register',
    link: routes.REGISTER,
    restricted: false,
    exclude: true,
  },
  {
    id: 4,
    type: 'navItem',
    icon: 'sign-in-alt',
    text: 'Login',
    link: routes.LOGIN,
    restricted: false,
    exclude: true,
  },
  {
    id: 5,
    type: 'navItem',
    icon: 'file-alt',
    text: 'My reviews',
    link: routes.USER_REVIEWS,
    restricted: true,
  },
  {
    id: 6,
    type: 'navItem',
    icon: 'edit',
    text: 'Add reviews',
    link: routes.ADD_TRIP,
    restricted: true,
  },
  {
    id: 7,
    type: 'navItem',
    icon: 'sign-out-alt',
    text: 'Logout',
    link: routes.LOGOUT,
    restricted: true,
  },
];
